version: "3.7"
services:
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    hostname: portainer
    networks:
      - hostnet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/portainer/data:/data"

networks:
  hostnet:
    name: host
    external: true
